Mostly fixes prefix generation when hostnames start with a digit, consilidated some functionality into functions and made confd error story more robust

diff --git a/hostconfig b/hostconfig
--- a/hostconfig
+++ b/hostconfig
@@ -5,8 +5,10 @@ pushd "$( cd "$(dirname "$0")" ; pwd -P )" > /dev/null
 OPT_CONFIG="${HOSTCONFIG_CONFIG:-'/etc/hostconfig/hostconfig.conf'}"
 
 new() {
-  local prefix=''
-  generate_prefix "$FILENAME"
+  if [[ -f $SETTINGSPATH ]] && [[ -z $DO_FORCE ]]; then
+    return $(err "Config already exists, run with --force to override settings"); fi
+
+  local prefix; prefix_resolution "$FILENAME"
 
 cat << EOF > "$TOMLCONFIGPATH"
 [template]
@@ -26,11 +28,8 @@ keys = [
 ]
 check_cmd = "nginx -t -c {{.src}}"
 reload_cmd = "service nginx reload"
+
 EOF
-
-  if [[ -f $SETTINGSPATH ]] && [[ -z $DO_FORCE ]]; then
-    return $(err "Tenant already exists, run with --force to override settings"); fi
-
 cat << EOF > "$SETTINGSPATH"
 # PRIMARYHOST is only used within settings, not available in confd tmpl
 PRIMARYHOST=$SETTING_PRIMARYHOST
@@ -42,26 +41,26 @@ FULLREDIRECT_TOHOST=$SETTING_FULLREDIRECT_TOHOST
 # Partial redirect is just the default redirects to help prevent redirect loop
 PARTIALREDIRECT_HOSTNAMES=$SETTING_PARTIALREDIRECT
 PARTIALREDIRECT_TOHOST=$SETTING_PARTIALREDIRECT_TOHOST
-
 EOF
+
   # By default enable config by setting DO_DISABLE=false
   if [[ ! $DO_DISABLE ]]; then DO_DISABLE=false; fi
-  apply_opts && run_confd $FILENAME
+  apply_opts && run_confd "$FILENAME" || return 1
 }
 
-update() { apply_opts && run_confd $FILENAME; }
+update() { apply_opts && run_confd "$FILENAME" || return 1; }
 update-all() {
-  local DO_ALL=true;
-  echo -e "${color_yellow}Ignoring all other option flags when running update-all ${color_norm}"
-  run_confd
+  # TODO Repurpose hostname_pattern for grep pattern of which files to update
+  warn "Ignoring all other option flags when running update-all"
+  local DO_ALL=true; run_confd || return 1
 }
 
 delete() {
   if [[ ! $DO_FORCE ]]; then
-    echo -e "${color_yellow}Deleting ${FILENAME}.toml and moving ${FILENAME}.env to .old, use --force to delete all${color_norm}"
-     mv -f "$SETTINGSPATH" "$SETTINGSPATH.old"
+    warn "Deleting ${FILENAME}.toml and moving ${FILENAME}.env to .old, use --force to delete all"
+    mv -f "$SETTINGSPATH" "$SETTINGSPATH.old"
   else
-    echo -e "${color_yellow}Deleting ${FILENAME}.{toml,env} and ${FILENAME}.env${color_norm}"
+    warn "Deleting ${FILENAME}.{toml,env} and nginx enabled and available config files"
     rm -f "$SETTINGSPATH"
   fi
 
@@ -70,49 +69,42 @@ delete() {
 }
 
 apply_opts() (
-  change_settingkey() { grep -q "^${1}=" "$SETTINGSPATH" && sed -i '' "s/^${1}=.*/${1}=${2}/" "$SETTINGSPATH" || echo -e "$2" >> "$SETTINGSPATH"; }
+  read_settingkey() { match=$(grep -q "^${1}=" "$SETTINGSPATH"); match="${match#=}"; }
+  change_settingkey() { grep -q "^${1}=" "$SETTINGSPATH" && (sed -i.bak "s/^${1}=.*/${1}=${2}/" "$SETTINGSPATH"; rm -f "$SETTINGSPATH.bak") || echo -e "$1=$2" >> "$SETTINGSPATH"; }
   remove_settingkey() { sed -n -i '' "/^${1}=/!p" "$SETTINGSPATH"; }
 
   if [[ $DO_BAREHOST = true ]]; then
-    change_settingkey 'ISBAREHOST' 'ISBAREHOST=Fully remove this line to render redirects etc.'
+    change_settingkey 'ISBAREHOST' 'Fully remove this line to render redirects etc.'
   elif [[ $DO_BAREHOST = false ]]; then
     remove_settingkey 'ISBAREHOST'
   fi
 
   if [[ $DO_HTTP = true ]]; then
-    change_settingkey 'ISHTTP' 'ISHTTP=Fully remove this line to use https.'
+    change_settingkey 'ISHTTP' 'Fully remove this line to use https.'
   elif [[ $DO_HTTP = false ]]; then
     remove_settingkey 'ISHTTP'
   fi
 
   if [[ $DO_UNLISTED = true ]]; then
-    change_settingkey 'ISUNLISTED' 'ISUNLISTED=Fully remove this line to go listed.'
+    change_settingkey 'ISUNLISTED' 'Fully remove this line to go listed.'
   elif [[ $DO_UNLISTED = false ]]; then
     remove_settingkey 'ISUNLISTED'
   fi
 
+  local match
+  if [[ -z $DO_DISABLE ]]; then
+    read_settingkey 'ISDISABLED'; DO_DISABLE="$match"; fi
+
   if [[ $DO_DISABLE = true ]]; then
+    change_settingkey 'ISDISABLED' 'true'
     rm -f "$NGINXENABLEDPATH/$FILENAME" >/dev/null 2>&1
   elif [[ $DO_DISABLE = false ]]; then
+    change_settingkey 'ISDISABLED' 'false'
     # Too bad bash has no functionality for this
     local relpath=$(perl -e 'use File::Spec; print File::Spec->abs2rel(@ARGV) . "\n"' "$NGINXAVAILABLEPATH" "$NGINXENABLEDPATH")
     ln -s "$relpath/$FILENAME" "$NGINXENABLEDPATH/$FILENAME" >/dev/null 2>&1
   fi
-
-  if [[ $DO_WWW ]]; then
-    change_settingkey 'FULLREDIRECT_HOSTNAMES' ".$TEMPLATE_HELPER_PRIMARYHOST"
-    change_settingkey 'PARTIALREDIRECT_HOSTNAMES' "www.$TEMPLATE_HELPER_PRIMARYHOST"
-
-    if [[ $OPT_PRIMARY = 'www.'* ]]; then
-      change_settingkey 'PARTIALREDIRECT_HOSTNAMES' "$TEMPLATE_HELPER_PRIMARYHOST"
-      change_settingkey 'FULLREDIRECT_HOSTNAMES' "$TEMPLATE_HELPER_PRIMARYHOST"
-    elif [[ ! -z $OPT_PRIMARY ]] && [[ ! $INPUT_HOSTPATTERN = ".$OPT_PRIMARY" ]]; then
-      # If primary with www and not root domain then add full www to partial redirect
-      change_settingkey 'PARTIALREDIRECT_HOSTNAMES' ".$TEMPLATE_HELPER_PRIMARYHOST";
-    elif [[ ! -z $OPT_PRIMARY ]] && [[ $INPUT_HOSTPATTERN = ".$OPT_PRIMARY" ]]; then
-      change_settingkey 'PARTIALREDIRECT_HOSTNAMES' "$TEMPLATE_HELPER_PRIMARYHOST";
-    fi
-  fi
+  return 0;
 )
 
 filename_resolution() {
@@ -129,6 +121,19 @@ hostname_resolution() {
   host="${1#'*.'}"
   # If www, change primary host .example.com to example.com
   host="${host#'.'}"
+}
+
+prefix_resolution() {
+  # Only keep 0-9a-zA-Z as prefixes (i.c.w. env vars) can only be in that format for confd
+  prefix=$(echo $1 | sed 's/[^0-9a-zA-Z]*//g');
+
+  # Prefix wildcard domains and domains starting with a digit
+  # To help with diagnostics and to prevent env var restriction issues
+  if [[ $1 =~ ^[[:digit:]] ]]; then
+    prefix="x$prefix";
+  elif [[ $1 = '_'* ]]; then
+    prefix="wc$prefix";
+  fi
 }
 
 main() {
@@ -161,29 +166,20 @@ main() {
   SETTING_PRIMARYHOSTNAMES="$TEMPLATE_HELPER_PRIMARYHOST"
   SETTING_FULLREDIRECT_TOHOST="$TEMPLATE_HELPER_PRIMARYHOST"
   SETTING_PARTIALREDIRECT_TOHOST="$TEMPLATE_HELPER_PRIMARYHOST"
-  SETTING_FULLREDIRECT="\"*.$TEMPLATE_HELPER_SECONDARYHOST $TEMPLATE_HELPER_SECONDARYHOST\""
-  SETTING_PARTIALREDIRECT="*.$TEMPLATE_HELPER_SECONDARYHOST"
 
   if [[ $DO_EXACT ]]; then
-    SETTING_FULLREDIRECT="$SECONDARYHOST"
-    SETTING_PARTIALREDIRECT="$SECONDARYHOST"
+    SETTING_FULLREDIRECT="\"$SECONDARYHOST\""
+    SETTING_PARTIALREDIRECT="\"$SECONDARYHOST\""
+  else
+    SETTING_FULLREDIRECT="\"*.$TEMPLATE_HELPER_SECONDARYHOST $TEMPLATE_HELPER_SECONDARYHOST\""
+    SETTING_PARTIALREDIRECT="\"*.$TEMPLATE_HELPER_SECONDARYHOST\""
   fi
 
   if [[ $OPT_PRIMARY ]] && [[ ! $PRIMARYHOST = $SECONDARYHOST ]]; then
     SETTING_PARTIALREDIRECT="$SETTING_FULLREDIRECT"
   fi
 
-  $INPUT_COMMAND # Run command (e.g. new or update)
-}
-
-generate_prefix() {
-  # Remove all underscores as confd has a hard time with underscores in prefixes and env vars
-  prefix="${1//_/}"
-
-  if [[ $1 = '_'* ]]; then
-    # Prefix a wildcard domain with wc to help with diagnostics
-    prefix="wc$prefix";
-  fi
+  $INPUT_COMMAND; exit $? # Run command (e.g. new or update)
 }
 
 # Parentheses funcs are run in sub-shells so cleanup is immediately after end of func
@@ -221,8 +217,7 @@ run_confd() (
       fi
     done < "$settingspath"
 
-    local prefix=''
-    generate_prefix "$filename"
+    local prefix; prefix_resolution "$filename"
 
     # Need to export like this to avoid quotes around value
     local uppername=$(echo "$prefix" | tr '[:lower:]' '[:upper:]')
@@ -238,13 +233,27 @@ run_confd() (
 
     # Set filename to the one for the current operation
     export "${uppername}_FILENAME=${1}"
-    echo -e "${color_green}Processing \"${settingspath##*/}\" settings...${color_norm}"
+    progress "Processing '${settingspath##*/}' settings..."
   done
 
-  local sync=${DO_SYNCONLY:+'-sync-only'}
-  echo -e "${color_green}Running confd...${color_norm}"
-  $CONFD -onetime -backend env $sync -confdir "$confdir" 2>&1 | tee -a "$CONFDLOG"
+  local sync=${DO_SYNCONLY:+'-sync-only'} debug=${DO_DEBUG:+'-log-level debug'}
+  CONFDCOMMAND="$CONFD -onetime  -backend env $debug $sync -confdir $confdir"
+  progress "Running confd command"
+
+  set -o pipefail
+  if $CONFDCOMMAND 2>&1 | tee -a "$CONFDLOG"; then return 0;
+  else confd-cleanup || return 1; fi
+  set +o pipefail
 )
+
+confd-cleanup() {
+  err "Confd ran into issues while executing, see confd.log for more info"
+  if [[ $INPUT_COMMAND = 'new' ]]; then
+    # rm -f "$TOMLCONFIGPATH" "$NGINXAVAILABLEPATH/$FILENAME" "$NGINXENABLEDPATH/$FILENAME";
+    mv "$SETTINGSPATH" "$SETTINGSPATH.old"
+  fi
+  return 1;
+}
 
 check_input() {
   if [[ -z $1 ]]; then
@@ -275,14 +284,19 @@ check_input() {
       return $(err_help "Primary host has to be an absolute host, not a pattern"); fi
 
   case "$OSTYPE" in
-  darwin*) CONFD="${CONFDFILEPREFIX}darwin";;
-  linux*)  CONFD="${CONFDFILEPREFIX}linux" ;;
-  *)       return $(err "No supported confd binary for: $OSTYPE, see https://github.com/kelseyhightower/confd to build from source.") ;;
+    darwin*) CONFD="${CONFDFILEPREFIX}darwin";;
+    linux*)  CONFD="${CONFDFILEPREFIX}linux" ;;
+    *)       return $(err "No supported confd binary for: $OSTYPE, see https://github.com/kelseyhightower/confd to build from source.") ;;
   esac
 }
 
-err() { echo -e "${color_red}Error: ${1}${color_norm}\n" >&2; return 1; }
-err_help() { echo -e "$HELP\n${color_red}Error: ${1}${color_norm}\n" >&2; return 1; }
+c_start="\033[" c_norm="${c_start}0m" c_red="${c_start}0;91m"
+c_yellow="${c_start}0;33m" c_green="${c_start}0;32m"
+info() { echo -e "Info: ${1}"; return 0; }
+progress() { echo -e "${c_green}Progress: ${1}${c_norm}"; }
+warn() { echo -e "${c_yellow}Warning: ${1}${c_norm}\n"; return 0; }
+err() { echo -e "${c_red}Error: ${1}${c_norm}\n" >&2; return 1; }
+err_help() { echo -e "$HELP\n${c_red}Error: ${1}${c_norm}\n" >&2; return 1; }
 
 parse_args() {
   _parse_args 1 "$@";
@@ -351,11 +365,6 @@ parse_options() {
     esac
   done
 }
-
-if [[ -z "${color_start-}" ]]; then
-  color_start="\033[" color_norm="${color_start}0m" color_red="${color_start}0;91m"
-  color_yellow="${color_start}0;33m" color_green="${color_start}0;32m"
-fi
 
 read -r -d '' HELP<<"EOF"
 Usage: hostconfig [OPTIONS] COMMAND <hostname_pattern> [SETTINGS]
